USE [NY_ORDER]
GO
/****** Object:  StoredProcedure [dbo].[P_DEL_AGEN_DATA]    Script Date: 2022-03-15 오후 12:52:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[P_DEL_AGEN_DATA]
(
	@I_AGEN_CD nvarchar(20)
)
AS
BEGIN
	
	SET NOCOUNT ON;

	BEGIN TRY

		BEGIN
			
			DELETE FROM T_MIG_FILE WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*마이그레이션 테이블*/
			DELETE FROM T_RCBOD_DTL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*자료실 내용*/

			DELETE FROM T_CNSG_ORD_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*위탁거래처 마스터*/
			DELETE FROM T_CNSG_ORD_PRD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*위탁거래처 상품*/
			DELETE FROM T_OTH_COM_PRMT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*타사 판촉물 입고 관리*/
			DELETE FROM T_PRMT_AGEN_RQST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*판촉물 소요량 요청*/
			DELETE FROM T_PRMT_AGEN_MNG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*판촉물 소요량 입고 관리*/
			
			DELETE FROM T_CRTB_RTGD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_ORD_RTGD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_ORD_STUS_PRD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_ORD_DLV_DTL  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_ORD_STUS_MST  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_ORD_DLV WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_ORD_PRD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			DELETE FROM T_OTH_COM_PRMT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*타사 판촉물 입고 관리*/
			DELETE FROM T_OTH_ORD_PRD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*타사제품 매입*/
			DELETE FROM T_ORD_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD
			
			--DELETE FROM T_PRMT_RQST_MNG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*판촉물 요청 기간 관리*/
			--DELETE FROM T_PRMT_PRD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*판촉물 자재 관리*/
			DELETE FROM T_PRMT_AGEN_RQST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*판촉물 소요량 요청*/
			DELETE FROM T_PRMT_AGEN_MNG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*판촉물 소요량 입고 관리*/

			--DELETE FROM T_CST_DIRET_HIS WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*애음자 이사 내역*/
			DELETE FROM T_CST_PRD_DLVY WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*애음자 배송 내역*/
			DELETE FROM T_CST_DLV_NTC WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*대리점 전달사항*/
			DELETE FROM T_CST_AREA_HIS WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*애음자 지역변경 내역*/
			DELETE FROM T_CST_PRD_UNTPC WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*제품별 계약 단가*/
			--DELETE FROM T_CST_PTTN_DTL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*애음자 패턴 설정 테이블*/
			DELETE FROM T_CST_PTTN  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*패턴 설정*/
			DELETE FROM T_CST_PRD_HIS WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 히스토리*/
			DELETE FROM T_CST_PRD_STPG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*제품 보류/중지*/
			DELETE FROM T_CST_PRD_PRMT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*애음자 제품 판촉물*/
			DELETE FROM T_CST_PRD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품*/
			DELETE FROM T_CST_BILCT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*수금*/
			DELETE FROM T_CST_DLV_ORDR WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*지역/애음자 배달순서*/
			DELETE FROM T_CST_RECP_HIS WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*애음자별 현금영수증 발행 이력*/
			/*DELETE FROM T_CST_SALE WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	애음자 판매*/
			DELETE FROM T_CST_LOG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*애음자 전체 로그*/ 
			DELETE FROM T_CST_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*애음자 마스터*/
		
			DELETE FROM T_INVRY_LOG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*재고 로그*/
			DELETE FROM T_INVRY_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*재고 마스터*/

			DELETE FROM T_STDR_PRD_SPPRC WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 기준 단가*/
			DELETE FROM T_PRD_BND_CHG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 일괄변경*/
			DELETE FROM T_PRD_UNTPC_HIS  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 단가 히스토리*/
			DELETE FROM T_PRD_AGEN_GRP WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 대리점 그룹*/
			DELETE FROM T_AGEN_PRD_UNTPC WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*대리점 지역별 제품 단가*/
			DELETE FROM T_CST_PRD_SPPRC WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*애음자 표준단가*/
			--DELETE FROM T_PRD_HOP WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 홉수 삭제할 수도 있음*/
			
			DELETE FROM T_PRD_DTL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*제품 상세*/
	
			DELETE FROM T_BA_BILL_TOT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*방판 수금 집계*/
			DELETE FROM T_BA_SALE_DTL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*방판 판매 디테일*/
			DELETE FROM T_BA_SALE_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*방판 판매 마스터*/

			DELETE FROM T_SI_BILL_TOT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*시판 수금 집계*/
			DELETE FROM T_SI_SALE_DTL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*시판 판매 디테일*/
			DELETE FROM T_SI_SALE_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*시판 판매 마스터*/
			DELETE FROM T_SI_VEND_CHAG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*시판 거래처(고객) 담당자*/
			DELETE FROM T_SI_VEND_MST WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD    /*시판 거래처(고객) 마스터*/

			DELETE FROM T_AGEN_EMPL_BKMK WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*대리점 사원 즐겨찾기*/
			DELETE FROM T_AGEN_VEND_SPRT WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*거래처 지원*/
			DELETE FROM T_AGEN_VEND_UNTPC  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*거래처별 단가 관리*/
			DELETE FROM T_AGEN_OTR_PUCH  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*매입처(메이저 x)*/
			DELETE FROM T_AGEN_PRD_UNTPC  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*지역별 제품 단가*/
			DELETE FROM T_AGEN_AREA  WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*지역*/
			DELETE FROM T_AGEN_ACCT_INFO WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*계좌정보*/
			
			DELETE FROM T_AGEN_EMPL_ROLE WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD 	/*대리점 권한*/
			DELETE FROM T_AGEN_MENU_ROLE WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD 	/*대리점 메뉴권한*/
			DELETE FROM T_AGEN_EMPL_HIS WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD 	/*로그인 히스토리*/
			DELETE FROM T_AGEN_EMPL_PWD WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*비밀번호*/
			DELETE FROM T_VEND_UNTPC_CHG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*거래처 단가 변경*/

			DELETE FROM T_AGEN_VEND_EMPL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*거래처 대리점 관리자*/
			DELETE FROM T_AGEN_VEND WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*거래처*/
			DELETE FROM T_AGEN_PRD_CHG WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD	/*제품 일괄 변경(지역,애음자)*/
			DELETE FROM T_AGEN_MENU_ROLE WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*메뉴 그룹 권한*/
			DELETE FROM T_AGEN_LSMTH WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD /*대리점 익월자료 생성 여부 테이블 */
			DELETE FROM T_AGEN_EMPL WHERE 1=1 AND AGEN_SEQ = @I_AGEN_CD --  AND EMPL_SEC_CD <> 'STOR_OWNR' 		

		END

	END TRY
	BEGIN CATCH
		ROLLBACK TRAN 		-- 실패
        
	END CATCH  
	
	SET NOCOUNT OFF
END
