USE [NY_ORDER]
GO
/****** Object:  UserDefinedFunction [dbo].[F_GET_UNTPC_DT]    Script Date: 2022-03-15 오후 12:59:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		DJ
-- Create date: 2022-03-07
-- Description:	판매등록일
-- =============================================
ALTER FUNCTION [dbo].[F_GET_UNTPC_DT]
(
	@I_AGEN_SEQ	NUMERIC(13)
	, @I_AREA_SEQ NUMERIC(13)
	, @I_CST_SEQ NUMERIC(13)
	, @I_PRD_SEQ NUMERIC(13)
	, @I_PRD_DTL_SEQ NUMERIC(13)
	, @I_CST_PRD_SEQ NUMERIC(13)
	, @I_PTTN_SEQ NUMERIC(13)
)
RETURNS VARCHAR(8)
AS
BEGIN
	DECLARE @V_UNTPC NUMERIC(13,2)
			, @V_UNTPC_DT VARCHAR(8)
			, @O_UNTPC_DT VARCHAR(8)
			, @V_STDR_CNT INT
			, @V_STDR_EMPL_CNT INT
			, @V_STDR_CST_CNT INT
			, @V_AGEN_PRD_CNT INT
			, @V_CST_PRD_CNT INT
			, @V_CST_PRD_U_CNT INT
		--, @O_REG_DT VARCHAR(8)
	
	/*1. 제품 마스터 UNTPC(매입가(SPPRC+VAT_SPPRC))*/
	BEGIN
		SELECT 
			@O_UNTPC_DT = UNTPC_APPL_DT
		FROM
			T_PRD_MST
		WHERE
			1=1
			AND PRD_SEQ = @I_PRD_SEQ
	END

	/*2. T_STDR_PRD_SPPRC(제품 기준 단가)->UNTPC(매입가) 6순위 */
	BEGIN 
		SELECT 
			@V_STDR_CNT= COUNT(*)
		FROM 
			T_STDR_PRD_SPPRC
		WHERE 
		1=1
		AND AGEN_SEQ = @I_AGEN_SEQ
		AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
		
		IF @V_STDR_CNT > 0
		BEGIN
			SELECT 
				@V_UNTPC = (CASE 
					WHEN UNTPC IS NULL THEN ISNULL(SPPRC, 0) + ISNULL(VAT,0)
					WHEN UNTPC IS NULL AND SPPRC IS NULL AND VAT IS NULL THEN 0
				ELSE UNTPC END)
				, @V_UNTPC_DT = APPL_DT
			FROM 
				T_STDR_PRD_SPPRC
			WHERE 
			1=1
			AND AGEN_SEQ = @I_AGEN_SEQ
			AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
			AND LAST_YN = 'Y'
		END
		IF @V_UNTPC > 0
		BEGIN
			SET @O_UNTPC_DT = @V_UNTPC_DT
		END
	END

	/*3. T_STDR_PRD_SPPRC(제품 기준 단가)->CST_UNTPC(애음자 판매가) 4순위 */
	BEGIN
		SELECT 
			@V_STDR_EMPL_CNT= COUNT(*)
		FROM 
			T_STDR_PRD_SPPRC
		WHERE 
		1=1
		AND AGEN_SEQ = @I_AGEN_SEQ
		AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
		AND EMPL_UNTPC IS NOT NULL

		IF @V_STDR_EMPL_CNT > 0
		BEGIN
			SELECT 
				@V_UNTPC = EMPL_UNTPC
				,  @V_UNTPC_DT = APPL_DT
			FROM 
				T_STDR_PRD_SPPRC
			WHERE 
			1=1
			AND AGEN_SEQ = @I_AGEN_SEQ
			AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
			AND LAST_YN = 'Y'
		END
		
		IF @V_UNTPC > 0
		BEGIN
			SET @O_UNTPC_DT = @V_UNTPC_DT
		END
	END
	
	/*4. T_AGEN_PRD_UNTPC(대리점 지역별 제품 단가)->UNTPC(지역 표준 단가(지역별 판매가)) 3순위 */
	BEGIN
		SELECT 
			@V_AGEN_PRD_CNT = COUNT(*)
		FROM 
		T_AGEN_PRD_UNTPC
		WHERE 
		1=1
		AND AGEN_SEQ = @I_AGEN_SEQ
		AND AREA_SEQ = @I_AREA_SEQ
		AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
		AND LAST_YN = 'Y'
		
		IF @V_AGEN_PRD_CNT > 0
		BEGIN
			SELECT 
				@V_UNTPC = UNTPC
				,  @V_UNTPC_DT = APPL_DT
			FROM 
			T_AGEN_PRD_UNTPC
			WHERE 
			1=1
			AND AGEN_SEQ = @I_AGEN_SEQ
			AND AREA_SEQ = @I_AREA_SEQ
			AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
			AND LAST_YN = 'Y'
		END

		IF @V_UNTPC > 0
		BEGIN
			SET @O_UNTPC_DT = @V_UNTPC_DT
		END
	END

	/*5. T_CST_PRD_SPPRC(애음자 표준단가)->UNTPC(판매가) 2순위 */
	BEGIN
		SELECT 
			@V_CST_PRD_CNT = COUNT(*)
		FROM 
			T_CST_PRD_SPPRC
		WHERE 
		1=1
		AND AGEN_SEQ = @I_AGEN_SEQ
		AND AREA_SEQ = @I_AREA_SEQ
		AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
		AND LAST_YN = 'Y'

		IF @V_CST_PRD_CNT > 0
		BEGIN
			SELECT 
				@V_UNTPC = UNTPC
				,  @V_UNTPC_DT = APPL_DT
			FROM 
				T_CST_PRD_SPPRC
			WHERE 
			1=1
			AND AGEN_SEQ = @I_AGEN_SEQ
			AND AREA_SEQ = @I_AREA_SEQ
			AND PRD_DTL_SEQ = @I_PRD_DTL_SEQ
			AND LAST_YN = 'Y'
		END

		IF @V_UNTPC > 0
		BEGIN
			SET @O_UNTPC_DT = @V_UNTPC_DT
		END
	END

	/*6.T_CST_PRD_UNTPC(애음자 제품별 계약 단가)->UNTPC(판매가) 1순위*/
	BEGIN
	--@V_CST_PRD_U_CNT
		SELECT 
			@V_CST_PRD_U_CNT= COUNT(*)
		FROM 
		T_CST_PRD_UNTPC
		WHERE 
		1=1
		AND AGEN_SEQ = @I_AGEN_SEQ
		AND AREA_SEQ = @I_AREA_SEQ
		AND CST_SEQ = @I_CST_SEQ
		AND CST_PRD_SEQ = @I_CST_PRD_SEQ
		AND PTTN_SEQ = @I_PTTN_SEQ
		AND LAST_YN = 'Y'

		IF @V_CST_PRD_U_CNT > 0
		BEGIN
			SELECT 
				@V_UNTPC= UNTPC
				, @V_UNTPC_DT = STAT_DT
			FROM 
			T_CST_PRD_UNTPC
			WHERE 
			1=1
			AND AGEN_SEQ = @I_AGEN_SEQ
			AND AREA_SEQ = @I_AREA_SEQ
			AND CST_SEQ = @I_CST_SEQ
			AND CST_PRD_SEQ = @I_CST_PRD_SEQ
			AND PTTN_SEQ = @I_PTTN_SEQ
			AND LAST_YN = 'Y'
		END 

		IF @V_UNTPC > 0
		BEGIN
			SET @O_UNTPC_DT = @V_UNTPC_DT
		END
	END 
		
	RETURN @O_UNTPC_DT
END
